<?php

namespace app\index\controller;

use think\Controller;
use think\Request;

class Collection extends Controller
{
    public $model;
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->model=model('User');
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken1();
    }
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $uid=$this->request->uid;
        $result=$this->model->queryOne(['uid'=>$uid]);
        if ($result){
//            $result['collection']=explode(',',$result['collection']);
            $model=model('Stayhome');
            $collection=$result['collection'];
            $category=$model->getCollection('sid','in',$collection);
            if ($category){
                return json([
                    'code'=>200,
                    'msg'=>'查询成功',
                    'data'=>$category
                ]);
            }else{
                return json([
                    'code'=>200,
                    'msg'=>'暂无数据',
                ]);
            }

        }else{
            return json([
                'code'=>404,
                'msg'=>'查询失败',
            ]);
        }
        //
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data=$request->post();
        $model=model('User');
        $where['uid']=$this->request->uid;
        $result=$model->collection($where,$data);
        if ($result){
            return json([
                'code'=>200,
                'msg'=>'收藏成功',
            ]);
        }else{
            return json([
                'code'=>400,
                'msg'=>'收藏失败',
            ]);
        }
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
